- taxi_nosql/create_random_passenger_data.py
> Fixed CSV header

- taxi_streaming/cleanup_stream.sh
- taxi_streaming/consume_taxi_to_kv.py
- taxi_streaming/create_random_driver_data.py
- taxi_streaming/create_random_driver_data.sh
- taxi_streaming/create_taxi_stream.sh
- taxi_streaming/spark-submit_cmd
- taxi_streaming/stream_driver_data.py
- taxi_streaming/stream_driver_data.sh
The changes include expanding the use of variables, fixing the Python applications to comply with PEP8, and code-comments editing
> taxi_streaming code and comments review changes

- taxi_streaming/create_random_drivers_data.sh
Variable renaming for consistency with *stream_drivers_data.py*
> create_random_drivers_data.sh: Rename STREAM_DATA_INPUT_FILE to INPUT_FILE

- taxi_streaming/consume_drivers_stream_data.py
- taxi_streaming/stream_drivers_data.py
Python syntax fixes for PR #10 and PR #13 to comply with PEP8
I checked all update **taxi_streaming** Python applications with a PEP8 validator.
> taxi_streaming: PEP8 syntax fixes for PR 10 & PR 13

- taxi_streaming/README.md
> taxi_streaming example README: The "Containers" UI screen was renamed to "Data" in v1.5.0

- create_schema/README.md
- create_schema/create_schema.py
- create_schema/igz_nosql_web.py
> Improve usability through improved command line arguments

- create_schema/README.md
- create_schema/create_schema.py
- create_schema/igz_nosql_web.py
> DOC review for create_schema

- create_schema/README.md
> create_schema README: Add usage examples + quote schema-file type values

- CSV_to_Parquet/README.md
- GO HTTP API/README.md
- java-iguazio-api-examples/README.md
- postman/README.md
- taxi_nosql/Nuclio/README.md
- taxi_nosql/README.md
- taxi_nosql/nuclio_python/README.md
@NirSe  @yaronha I did a very basic doc review of the README files (which started out with fixing the product names and capitalization). Please merge the PR and then merge the changes to the master branch.
> Basic README files doc review

- taxi_streaming/README.md
MERGE  `master` PR #36 to `1.5`
@NirSe Please merge.
> [DOC REVIEW] taxi_nosql Python code-comments review

- taxi_nosql/igz_nosql_web.py
- taxi_nosql/nuclio_python/generate_data.py
- taxi_nosql/nuclio_python/ingest.py
> [DOC] taxi_nosql Python code-comments review

- taxi_nosql/nuclio_python/functions/generate_data/generate_data.py
- taxi_nosql/nuclio_python/functions/ingest/ingest.py
@NirSe Both functions now pass PEP8 validation. Please review, test, and merge.
> [DOC] taxi nosql/nuclio python functions PEP8 validation & cosmetic fixes + comments review [IG-7915]

- taxi_streaming/README.md
MERGE `master` PR #40 to `1.5`.
@NirSe Please merge.
> [DOC] taxi_streaming README: Add %sh to hadoop fs cleanup command (v1.5)

- taxi_streaming/README.md
> [DOC] taxi_streaming README: Add %sh to hadoop fs cleanup command

- taxi_streaming/README.md
> [DOC review] Minor taxi_streaming README editing (align with doc site)

- taxi_streaming/README.md
- taxi_streaming/consume_drivers_stream_data.py
The changes were reviewed and approved by Nir before the commit.
@NirSe Please run the example to ensure that nothing was broken by the changes.
> taxi_streaming v1.7 API changes: add a V3IO_STREAM_PATH param; edit README

- taxi_streaming/README.md
MERGE `master` PR #59 to `1.7`
> {DOC] Taxi-Streaming Example README: Capitalize "Iguazio" (v1.7)

- taxi_streaming/README.md
MERGE `master` PR #59 to `1.5`
> [DOC] Taxi-Streaming Example README: Capitalize "Iguazio" (v1.5)

- taxi_streaming/README.md
MERGE `master` PR #64 to `1.7`
> [DOC] Taxi-Streaming Example README:  Use relative GH paths (MERGE PR #64 to 1.7)

- taxi_streaming/README.md
MERGE `master` PR #64 to `1.5`
> [DOC] Taxi-Streaming Example README:  Use relative GH paths (MERGE PR #64 to 1.5)

- taxi_streaming/README.md
MERGE `master` PR #68 to `1.7`
> [DOC] Taxi-Streaming Example README: Minor editing to the opening text [MERGE PR 68 to 1.7]

- taxi_streaming/README.md
MERGE `master` PR #68 to `1.5`
> [DOC] Taxi-Streaming Example README: Minor editing to the opening text [MERGE PR 68 to 1.5]

- netops_demo/golang/src/github.com/v3io/demos/functions/ingest/ingest.go
- netops_demo/py/functions/generate/generate.py
- netops_demo/py/functions/generate/generate_test.py
1. Sort metrics so that the proper metrics are created
2. Normalize company name to snake case for labels
> Fix netops generator creating more metrics than it should

- taxi_streaming/README.md
- taxi_streaming/consume_drivers_stream_data.py
MERGE `master` PR #83 & PR #85 to `1.7`.
> [1.7] taxi_streaming: revert to configuring the container with createDirectStream v3ioConfig
